# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.1
  - 1.4
  - 1.5
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
script:
  - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.test("ConcreteStructs")'
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
